// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    paths: {
      urlArgs: "bust=" + (new Date()).getTime(),
      baseUrl: '.',
      jquery: '../libs/jquery/jquery.min',
      ie8fadefix: 'jquery.ie8.fade.fix'
    },
    shim: {
      ie8fadefix: {
        deps: ['!jquery']
      }
    }
  });

  require(['iefix'], function() {});

}).call(this);
