// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    paths: {
      baseUrl: '.',
      jquery: '../libs/jquery/jquery.min',
      ie8fadefix: 'jquery.ie8.fade.fix'
    },
    shim: {
      ie8fadefix: {
        deps: ['jquery']
      }
    }
  });

}).call(this);
