// Generated by CoffeeScript 1.6.3
(function() {
  define(['ie8fadefix'], function() {
    $("#test-click").hover(function() {
      $("#test").fadeOut("slow");
    }, function() {
      $("#test").fadeIn("slow");
    });
  });

}).call(this);
