// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var html, oEventFadeIn, oEventFadeOut;
    html = $("html");
    if ($(html).hasClass("ie8") === false) {
      return false;
    }
    oEventFadeIn = jQuery.fn.fadeIn;
    jQuery.fn.fadeIn = function() {
      console.log(arguments);
      $(this).show();
    };
    oEventFadeOut = jQuery.fn.fadeOut;
    jQuery.fn.fadeOut = function() {
      $(this).hide();
    };
  });

}).call(this);
