// Generated by CoffeeScript 1.6.3
(function() {
  var html, oEventFadeIn, oEventFadeOut;

  html = $("html");

  if ($(html).hasClass("ie8") === false) {
    return false;
  }

  oEventFadeIn = jQuery.fn.fadeIn;

  jQuery.fn.fadeIn = function() {
    $(this).show();
    if (arguments[1] != null) {
      arguments[1].apply();
    }
  };

  oEventFadeOut = jQuery.fn.fadeOut;

  jQuery.fn.fadeOut = function() {
    $(this).hide();
    if (arguments[1] != null) {
      arguments[1].apply();
    }
  };

}).call(this);
